spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.13.1:1521:orcl
    username: nhansu
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      poolName: NhanSuConnectionPool
      maximumPoolSize: 10
      minimumIdle: 5
      idleTimeout: 30000
      maxLifetime: 1800000
      connectionTimeout: 30000
      leak-detection-threshold: 15000
      validation-timeout: 30000
      driverClassName: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
    show-sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  signerKey: 5L4xTlOiAtw1uO4gLfMoX00FQYSfQXXNTLgre41TSIicFjLYIiLg0HOCPCqe1ClL
  expirationTimeMinutes: 1200
cors:
  allowed-origins: "*"
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
app:
  store:
    path-upload: ../uploads